//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dans
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Datauch { get; set; }
        public string Adresuch { get; set; }
        public double Numberuch { get; set; }
        public double Numberrod { get; set; }
    }
}
