//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sveds
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public int Klassuch { get; set; }
        public string Ballyuch { get; set; }
        public string Uspevaemostuch { get; set; }
        public string Postzanuch { get; set; }
    
        public virtual KlassId KlassId { get; set; }
    }
}
